// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Drugs;
//
//    var drugCrime = DrugCrime.FromJson(jsonString);

namespace Drugs
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class DrugCrime
    {
        [JsonProperty("address_x")]
        public string AddressX { get; set; }

        [JsonProperty("latitude_x")]
        public string LatitudeX { get; set; }

        [JsonProperty("longitude_x")]
        public string LongitudeX { get; set; }

        [JsonProperty("agency")]
        public Agency Agency { get; set; }

        [JsonProperty("create_time_incident")]
        public DateTimeOffset CreateTimeIncident { get; set; }

        [JsonProperty("disposition_text", NullValueHandling = NullValueHandling.Ignore)]
        public string DispositionText { get; set; }

        [JsonProperty("event_number")]
        public string EventNumber { get; set; }

        [JsonProperty("incident_type_id")]
        public IncidentTypeId IncidentTypeId { get; set; }

        [JsonProperty("priority")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Priority { get; set; }

        [JsonProperty("closed_time_incident", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? ClosedTimeIncident { get; set; }

        [JsonProperty("beat", NullValueHandling = NullValueHandling.Ignore)]
        public String Beat { get; set; }

        [JsonProperty("community_council_neighborhood")]
        public string CommunityCouncilNeighborhood { get; set; }

        [JsonProperty("district", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? District { get; set; }

        [JsonProperty("arrival_time_primary_unit", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? ArrivalTimePrimaryUnit { get; set; }

        [JsonProperty("dispatch_time_primary_unit", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? DispatchTimePrimaryUnit { get; set; }
    }

    public enum Agency { Cpd };

    
    public enum IncidentTypeId { HeroinpCombined, HeronpPdOnly };

    public partial class DrugCrime
    {
        public static DrugCrime[] FromJson(string json) => JsonConvert.DeserializeObject<DrugCrime[]>(json, Drugs.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this DrugCrime[] self) => JsonConvert.SerializeObject(self, Drugs.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                AgencyConverter.Singleton,
                IncidentTypeIdConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class AgencyConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Agency) || t == typeof(Agency?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "CPD")
            {
                return Agency.Cpd;
            }
            throw new Exception("Cannot unmarshal type Agency");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Agency)untypedValue;
            if (value == Agency.Cpd)
            {
                serializer.Serialize(writer, "CPD");
                return;
            }
            throw new Exception("Cannot marshal type Agency");
        }

        public static readonly AgencyConverter Singleton = new AgencyConverter();
    }

    
    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }

    internal class IncidentTypeIdConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(IncidentTypeId) || t == typeof(IncidentTypeId?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "HEROINP-COMBINED":
                    return IncidentTypeId.HeroinpCombined;
                case "HERONP-PD ONLY":
                    return IncidentTypeId.HeronpPdOnly;
            }
            throw new Exception("Cannot unmarshal type IncidentTypeId");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (IncidentTypeId)untypedValue;
            switch (value)
            {
                case IncidentTypeId.HeroinpCombined:
                    serializer.Serialize(writer, "HEROINP-COMBINED");
                    return;
                case IncidentTypeId.HeronpPdOnly:
                    serializer.Serialize(writer, "HERONP-PD ONLY");
                    return;
            }
            throw new Exception("Cannot marshal type IncidentTypeId");
        }

        public static readonly IncidentTypeIdConverter Singleton = new IncidentTypeIdConverter();
    }
}
